version: '2'

services:
  wordpress:
    container_name: "${project}_wordpress"
    image: wordpress
    user: $user_id
    ports:
      - 8080:80
    volumes:
      - ../content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_PASSWORD: "${database_password}"

  mysql:
    container_name: "${project}_database"
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: "${database_password}"
